# Generated by Django 2.0.6 on 2018-07-07 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_book_publishday'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishday',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 8, 1, 41, 30, 433153)),
        ),
    ]
