# Generated by Django 2.0.6 on 2018-07-08 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_book_publishday'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='statue',
            field=models.CharField(choices=[('published', '已出版'), ('publishing', '待出版'), ('forbiden', '禁书')], default='publishing', max_length=24),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishday',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 8, 17, 35, 35, 556870)),
        ),
    ]
